// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		int greaterThanHalf = 0;
		int lessOrEqualHalf = 0;
		for (int i=0; i<n; i++){
			double random = Math.random();
			if (random>0.5) {
				greaterThanHalf++;
			} else {
				lessOrEqualHalf++;
			}
		}
		System.out.println("> 0.5: "+greaterThanHalf+" times");
		System.out.println("<= 0.5: "+lessOrEqualHalf+" times");
		
		if (lessOrEqualHalf!=0){
			System.out.println("Ratio: "+(double)greaterThanHalf/lessOrEqualHalf);
		} 
	}
}
